---

- name: Instalando as dependencias do Docker
  apt:
    name: "{{ dependencias }}"
    state: present
    update_cache: yes
  tags:
    - deps

- name: Importando a chave do repositorio do Docker
  apt_key: 
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  tags:
    - repo

- name: Adicionando o Repositorio do Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes
  tags:
    - repo

- name: Instalando o Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  tags:
    - docker